name: Lint and Format Code Base

on: [pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Check Prettier Formatting
        run: npm run prettier
